# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
