# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20160501_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.TextField(default='http://s32.postimg.org/o1wle2qxh/course.png'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.TextField(default='http://s32.postimg.org/nnv9eh6tx/teacher.png'),
        ),
    ]
